src/Entity/Chaton.php
<?php

namespace App\Entity;

use App\Repository\ChatonRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ChatonRepository::class)
 */
class Chaton
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=50)
     */
    private $Nom;

    /**
     * @ORM\Column(type="boolean")
     */
    private $Sterilise;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Photo;

    /**
     * @ORM\ManyToOne(targetEntity=Categorie::class, inversedBy="chatons")
     * @ORM\JoinColumn(nullable=false)
     */
    private $Categorie;

    /**
     * @ORM\ManyToMany(targetEntity=Proprietaire::class, mappedBy="Chatons")
     */
    private $proprietaires;

    public function __construct()
    {
        $this->proprietaires = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $Nom): self
    {
        $this->Nom = $Nom;

        return $this;
    }

    public function isSterilise(): ?bool
    {
        return $this->Sterilise;
    }

    public function setSterilise(bool $Sterilise): self
    {
        $this->Sterilise = $Sterilise;

        return $this;
    }

    public function getPhoto(): ?string
    {
        return $this->Photo;
    }

    public function setPhoto(string $Photo): self
    {
        $this->Photo = $Photo;

        return $this;
    }

    public function getCategorie(): ?Categorie
    {
        return $this->Categorie;
    }

    public function setCategorie(?Categorie $Categorie): self
    {
        $this->Categorie = $Categorie;

        return $this;
    }

    /**
     * @return Collection<int, Proprietaire>
     */
    public function getProprietaires(): Collection
    {
        return $this->proprietaires;
    }

    public function addProprietaire(Proprietaire $proprietaire): self
    {
        if (!$this->proprietaires->contains($proprietaire)) {
            $this->proprietaires[] = $proprietaire;
            $proprietaire->addChaton($this);
        }

        return $this;
    }

    public function removeProprietaire(Proprietaire $proprietaire): self
    {
        if ($this->proprietaires->removeElement($proprietaire)) {
            $proprietaire->removeChaton($this);
        }

        return $this;
    }
}

src/Entity/Proprietaire.php
<?php

namespace App\Entity;

use App\Repository\ProprietaireRepository;
use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass=ProprietaireRepository::class)
 */
class Proprietaire
{
    /**
     * @ORM\Id
     * @ORM\GeneratedValue
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Nom;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $Prenom;

    /**
     * @ORM\ManyToMany(targetEntity=Chaton::class, inversedBy="proprietaires")
     */
    private $Chatons;

    public function __construct()
    {
        $this->Chatons = new ArrayCollection();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getNom(): ?string
    {
        return $this->Nom;
    }

    public function setNom(string $nom): self
    {
        $this->Nom = $nom;

        return $this;
    }

    public function getPrenom(): ?string
    {
        return $this->Prenom;
    }

    public function setPrenom(string $prenom): self
    {
        $this->Prenom = $prenom;

        return $this;
    }

    /**
     * @return Collection<int, Chaton>
     */
    public function getChatons(): Collection
    {
        return $this->Chatons;
    }

    public function addChaton(Chaton $chaton): self
    {
        if (!$this->Chatons->contains($chaton)) {
            $this->Chatons[] = $chaton;
        }

        return $this;
    }

    public function removeChaton(Chaton $chaton): self
    {
        $this->Chatons->removeElement($chaton);

        return $this;
    }
}

src/Form/ProprietaireType.php
<?php

namespace App\Form;

use App\Entity\Chaton;
use App\Entity\Proprietaire;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;

class ProprietaireType extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options): void
    {
        $builder
            ->add('Nom')
            ->add('Prenom')
            ->add('chatons', EntityType::class, [
                'class'=>Chaton::class,
                'choice_label'=>"nom",
                'multiple'=>true,
                'expanded'=>true
            ])
            ->add("ok", SubmitType::class, ["label"=>"OK"])
        ;
    }

    public function configureOptions(OptionsResolver $resolver): void
    {
        $resolver->setDefaults([
            'data_class' => Proprietaire::class,
        ]);
    }
}

src/Controller/ProprietaireController.php
<?php

namespace App\Controller;

use App\Entity\Proprietaire;
use App\Form\ProprietaireSupprimerType;
use App\Form\ProprietaireType;
use Doctrine\Persistence\ManagerRegistry;
use Symfony\Bundle\FrameworkBundle\Controller\AbstractController;
use Symfony\Component\HttpFoundation\Request;
use Symfony\Component\HttpFoundation\Response;
use Symfony\Component\Routing\Annotation\Route;

class ProprietaireController extends AbstractController
{
    /**
     * @Route("/proprietaires", name="app_proprietaires")
     */
    public function index(ManagerRegistry $doctrine): Response
    {
        //On va aller chercher les catégories dans la BDD
        //pour ça on a besoin d'un repository
        $repo = $doctrine->getRepository(Proprietaire::class);
        $proprietaires=$repo->findAll(); //select * transformé en liste de Propriétaires

        return $this->render('proprietaires/index.html.twig', [
            'proprietaires'=>$proprietaires
        ]);
    }

    /**
     * @Route("/proprietaire/chatons/{id}", name="app_proprietaire_chatons")
     */
    public function voirChaton($id, ManagerRegistry $doctrine): Response
    {
        $proprietaire = $doctrine->getRepository(Proprietaire::class)->find($id);
        //si on n'a rien trouvé -> 404
        if (!$proprietaire) {
            throw $this->createNotFoundException("Aucune proprietaire avec l'id $id");
        }

        return $this->render('proprietaires/voirChatons.html.twig', [
            'proprietaire' => $proprietaire,
            "chatons" => $proprietaire->getChatons()
        ]);
    }

    /**
     * @Route("/proprietaire/ajouter", name="app_proprietaire_ajouter")
     */
    public function ajouter(ManagerRegistry $doctrine, Request $request): Response
    {
        //créer le formulaire
        //on crée d'abord une catégorie vide
        $proprietaire=new Proprietaire();
        //à partir de ça je crée le formulaire
        $form=$this->createForm(ProprietaireType::class, $proprietaire);

        //On gère le retour du formulaire tout de suite
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            //l'objet proprietaire est rempli
            //on va utiliser l'entity manager de doctrine
            $em=$doctrine->getManager();
            //on lui dit qu'on veut mettre la proprietaire dans la table
            $em->persist($proprietaire);

            //on génère l'appel SQL (l'insert ici)
            $em->flush();

            //on revient à l'accueil
            return $this->redirectToRoute("app_proprietaires");
        }

        return $this->render("proprietaires/ajouter.html.twig",[
            "formulaire"=>$form->createView()
        ]);
    }

    /**
     * @Route("/proprietaire/modifier/{id}", name="app_proprietaire_modifier")
     */
    public function modifier($id, ManagerRegistry $doctrine, Request $request): Response{
        //créer le formulaire sur le même principe que dans ajouter
        //mais avec un proprietaire existant
        $proprietaire = $doctrine->getRepository(Proprietaire::class)->find($id);

        //je vais gérer le fait que l'id n'existe pas
        if (!$proprietaire){
            throw $this->createNotFoundException("Pas de proprietaire avec l'id $id");
        }

        //Si j'arrive là c'est qu'elle existe en BDD
        //à partir de ça je crée le formulaire
        $form=$this->createForm(ProprietaireType::class, $proprietaire);

        //On gère le retour du formulaire tout de suite
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            //l'objet proprietaire est rempli
            //on va utiliser l'entity manager de doctrine
            $em=$doctrine->getManager();
            //on lui dit qu'on veut mettre le proprietaire dans la table
            $em->persist($proprietaire);

            //on génère l'appel SQL (update ici)
            $em->flush();

            //on revient à l'accueil
            return $this->redirectToRoute("app_proprietaires");
        }

        return $this->render("proprietaires/modifier.html.twig",[
            "proprietaire"=>$proprietaire,
            "formulaire"=>$form->createView()
        ]);
    }

    /**
     * @Route("/proprietaire/supprimer/{id}", name="app_proprietaire_supprimer")
     */
    public function supprimer($id, ManagerRegistry $doctrine, Request $request): Response{
        //créer le formulaire sur le même principe que dans ajouter
        //mais avec une catégorie existante
        $proprietaire = $doctrine->getRepository(Proprietaire::class)->find($id);

        //je vais gérer le fait que l'id n'existe pas
        if (!$proprietaire){
            throw $this->createNotFoundException("Pas de proprietaire avec l'id $id");
        }

        //Si j'arrive là c'est qu'elle existe en BDD
        //à partir de ça je crée le formulaire
        $form=$this->createForm(ProprietaireSupprimerType::class, $proprietaire);

        //On gère le retour du formulaire tout de suite
        $form->handleRequest($request);
        if ($form->isSubmitted() && $form->isValid()){
            //l'objet proprietaire est rempli
            //on va utiliser l'entity manager de doctrine
            $em=$doctrine->getManager();
            //on lui dit qu'on supprime le proprietaire
            $em->remove($proprietaire);

            //on génère l'appel SQL (delete ici)
            $em->flush();

            //on revient à l'accueil
            return $this->redirectToRoute("app_proprietaires");
        }

        return $this->render("proprietaires/supprimer.html.twig",[
            "proprietaire"=>$proprietaire,
            "formulaire"=>$form->createView()
        ]);
    }
}

templates/proprietaires/ajouter.html.twig
{% extends 'base.html.twig' %}

{% block title %}Ajouter un propriétaire{% endblock %}

{% block body %}
    <h1>Ajouter un propriétaire</h1>
    {{ form(formulaire) }}
{% endblock %}

templates/proprietaires/index.html.twig
{% extends 'base.html.twig' %}

{% block title %}Gestion des propriétaires{% endblock %}

{% block body %}
    <style>
        .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
        .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
    </style>

    <table class="container">
        <h1>Les Propriétaires</h1>
        <table class="table table-striped">
            <tr>
                <th>Nom</th>
                <th>Prenom</th>
                <th></th>
                <th></th>
                <th></th>
            </tr>
            {% for p in proprietaires %}
                <tr>
                    <td>{{ p.Nom }}</td>
                    <td>{{ p.Prenom }}</td>
                    <td>
                        <a href="{{ path("app_proprietaire_modifier", {"id": p.id}) }}" class="btn btn-primary">modifier</a>
                    </td>
                    <td>
                        <a href="{{ path("app_proprietaire_supprimer", {"id": p.id}) }}" class="btn btn-danger">supprimer</a>
                    </td>
                    <td>
                        <a href="{{ path("app_proprietaire_chatons", {"id": p.id}) }}" class="btn btn-warning">chatons</a>
                    </td>
                </tr>
            {% endfor %}
        </table>
        <a href="{{ path("app_proprietaire_ajouter") }}" class="mt-5 btn btn-primary">Ajouter un propriétaire</a>
    </div>
{% endblock %}

templates/proprietaires/modifier.html.twig
{% extends 'base.html.twig' %}

{% block title %}Modifier un proprietaire{% endblock %}

{% block body %}
    <div class="example-wrapper">
        <h1>Modifier <i>{{ proprietaire.nom }}</i></h1>
        {{ form(formulaire) }}
    </div>
{% endblock %}

templates/proprietaires/supprimer.html.twig
    {% extends 'base.html.twig' %}

{% block title %}Supprimer un chaton{% endblock %}

{% block body %}
    <h1>Supprimer <i> {{ proprietaire.prenom }} {{ proprietaire.nom }} </i> ? </h1>
    {{ form(formulaire) }}
    {# Bouton pour annulé la suppression et retourner au menu #}
    <a href="{{ path("app_proprietaires") }}" class="btn btn-default">Retour</a>
{% endblock %}

templates/proprietaires/voirChatons.html.twig
{% extends 'base.html.twig' %}

{% block title %}Chatons du propriétaire {{ proprietaire.prenom }} {{ proprietaire.nom }}{% endblock %}

{% block body %}
<style>
    .example-wrapper { margin: 1em auto; max-width: 800px; width: 95%; font: 18px/1.5 sans-serif; }
    .example-wrapper code { background: #F5F5F5; padding: 2px 6px; }
</style>

<div class="container">
    <h1>Chatons du propriétaire {{ proprietaire.prenom }} {{ proprietaire.nom }}</h1>
    <div class="row">
        {% for c in chatons %}
            <div class="col col-3">
                <div class="card"><img src="{{ c.photo }}" alt=""
                                       class="card-img-top">
                    <div class="card-body">
                        <h2 class="card-title">{{ c.nom }}</h2>
                        {% if (c.sterilise == 0) %}
                            <span>Ce chaton n'est pas castrer</span>
                        {% elseif (c.sterilise == 1) %}
                            <span>Ce chaton est castrer</span>
                        {% endif %}
                        <div>
                            <a href="{{ path("app_chaton_modifier", {"id": c.id}) }}" class="btn btn-primary">modifier</a>
                            <a href="{{ path("app_chaton_supprimer", {"id": c.id}) }}" class="btn btn-danger">supprimer</a>
                        </div>
                    </div>
                </div>
            </div>
        {% endfor %}
    </div>
    <a href="{{ path("app_chaton_ajouter") }}" class="mt-5 btn btn-primary">Ajouter un chaton</a>
</div>
{% endblock %}